version: "3.5"

services:
  db_auth:
    container_name: db_auth
    restart: always
    ports:
      - "50432:5432"
    environment:
      - POSTGRES_PASSWORD=2611Server
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - /home/rusdev/vpn/Data:/var/lib/postgresql/data
    image: postgres:15.1
