version: "3.5"

services:
  database:
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=2611Server
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testsystem
      - PGDATA=/var/lib/postgresql/data/
    volumes:
      - /home/rusdev/vpn/data:/var/lib/postgresql/data
      - /home/userpro/socket:/var/run/postgresql  
    image: postgres:15.1
  
